### PR TITLE
fix(core/upload): disable file browser if control is disabled

### LINKED ISSUE #1276: [IxUpload] disabled and LOADING don't prevent opening the dialog with keyboard
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Navigate to a disabled IxUpload with Tab, or an IxUpload with state=LOADING and interact with it with Space or Enter. Then the file chooser popup will be opened. In the case of disabled, no filesChanged event will be fired. In the case of LOADING, the filesChanged event will be fired.

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.1.0

### Code to produce this issue.

```shell
Can be reproduces in the stackblitz of the IX Documentation simply by adding disabled or state="LOADING". https://stackblitz.com/run?file=src%2Fapp%2Fupload.ts
```

### PR DESCRIPTION
**Pull request by danielleroux**
## 💡 What is the current behavior?

GitHub Issue Number: Closes #1276 

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [x] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [x] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [x] 🏗️ Successful compilation (`pnpm build`, changes pushed)

### CODE REVIEW

File: packages/core/src/components/upload/upload.tsx [hunk 1]
```diff
@@ -208,8 +236,10 @@ export class Upload {
   }
 
   render() {
+    const disabled = this.disabled || this.state === UploadFileState.LOADING;
+    const { 'aria-label': ariaLabel = 'Upload files', ...a11y } = this.a11y;
     return (
-      <Host>
+      <Host {...a11y} aria-disable={disabled}>
```
Comment (AndreasBerliner) [inline packages/core/src/components/upload/upload.tsx:242]:
```suggestion
      <Host {...a11y} aria-disabled={disabled}>
```

**Review by AndreasBerliner — CHANGES_REQUESTED** [review]

**Review by AndreasBerliner — APPROVED** [review]
