### PR TITLE
fix(core/menu-avatar-item): use host for trigger target

### LINKED ISSUE #1105: ix-dropdown trigger in combination with ix-menu-avatar-item does not work
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

Hi with this issue I want to reopen the issue from #895 
We tested the functionality with the release 2.1.0 and we still have the same issue

Following the orginal issue text
----
Hi,

we want to add a language switch to our menu based on an ix-dropdown.
When I added the id of the ix-menu-item as the trigger value for the dropdown nothing happend.

To double check if I did something wrong I tried it with an ix-dropdown-item and with this element everything works fine

I also noticed that the menu-avatar is no longer part of the documentation.

Is this still supported and an issue or is it an old component that is no longer supported and we need another solution?

BR
Philipp

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.1.0

### Code to produce this issue.

```shell
<ix-menu>
  <ix-menu-avatar top="Name" initials="PS">
    <ix-dropdown-item id="dd-item" icon="globe" label="DropDownItem"></ix-dropdown-item>
    <ix-menu-avatar-item id="ma-item" icon="globe" label="MenuAvatarItem"></ix-menu-avatar-item>
  </ix-menu-avatar>
</ix-menu>


<ix-dropdown trigger="dd-item">
  <ix-dropdown-item label="1"></ix-dropdown-item>
  <ix-dropdown-item label="2"></ix-dropdown-item>
</ix-dropdown>

<ix-dropdown trigger="ma-item">
  <ix-dropdown-item label="1"></ix-dropdown-item>
  <ix-dropdown-item label="2"></ix-dropdown-item>
</ix-dropdown>
```

### PR DESCRIPTION
**Pull request by danielleroux**
## 💡 What is the current behavior?

GitHub Issue Number: Closes #1105 

## 🆕 What is the new behavior?

If the ix-dropdown-item is hosted inside a wrapper like `ix-menu-avatar-item` it is necessary to provide the trigger indicator on the host level.

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [x] 🦮 Accessibility (a11y) features were implemented
- [x] 🗺️ Internationalization (i18n) - no hard coded strings
- [x] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [x] 📄 Documentation was reviewed/updated (`yarn docs`)
- [x] 🧪 Unit tests were added/updated and pass (`yarn test`)
- [x] 📸 Visual regression tests were added/updated and pass (`yarn visual-regression`)
- [x] 🧐 Static code analysis passes (`yarn lint`)
- [x] 🏗️ Successful compilation (`yarn build`, changes pushed)

### CODE REVIEW

File: packages/core/src/components/dropdown/dropdown-controller.ts [hunk 1]
```diff
@@ -96,10 +96,10 @@ class DropdownController {
     }
   }
 
-  dismissAll(includeUids?: string[]) {
+  dismissAll(forceCloseIds: string[] = []) {
```
Comment (nuke-ellington) [inline packages/core/src/components/dropdown/dropdown-controller.ts:99]:
```suggestion
  dismissAll(ignoreBehaviorForIds: string[] = []) {
```

File: packages/core/src/components/dropdown/dropdown-controller.ts [hunk 2]
```diff
@@ -96,10 +96,10 @@ class DropdownController {
...
     this.dropdowns.forEach((dropdown) => {
       if (
-        !includeUids?.includes(dropdown.getId()) &&
+        !forceCloseIds.includes(dropdown.getId()) &&
```
Comment (nuke-ellington) [inline packages/core/src/components/dropdown/dropdown-controller.ts:102]:
```suggestion
        !ignoreBehaviorForIds.includes(dropdown.getId()) &&
```

**Review by nuke-ellington — COMMENTED** [review]
Possible parameter renaming

**Review by nuke-ellington — APPROVED** [review]
