### PR TITLE
fix(core/validation-tooltip): prevent assignment/reading on null element

### LINKED ISSUE #944: TypeError: Cannot read properties of null (reading 'removeEventListener') at ValidationTooltip.call
### What happened?

All jest tests that involve interacting with a field utilizing an IxValidationTooltip are failing with the error quoted below. This has been happening for us since Ix 1.6.x but it didn't fail the tests, it would just clog up the console (which was difficult to work around in itself). Now (hundreds of) tests are failing and we haven't been able to find a solution on our end.

> TypeError: Cannot read properties of null (reading 'removeEventListener')
>     at ValidationTooltip.call (C:\Users\z004asyt\workspace\greactions\node_modules\@siemens\ix\components\src\components\validation-tooltip\validation-tooltip.tsx:190:22)
>     at ValidationTooltip.disconnectedCallback (C:\Users\z004asyt\workspace\greactions\node_modules\@stencil\core\internal\client\index.js:2586:46)
>     at ValidationTooltip.invokeTheCallbackFunction (C:\Users\z004asyt\workspace\greactions\node_modules\jsdom\lib\jsdom\living\generated\Function.js:23:26)
>     at invokeCEReactions (C:\Users\z004asyt\workspace\greactions\node_modules\jsdom\lib\jsdom\living\helpers\custom-elements.js:188:31)
>     at ceReactionsPostSteps (C:\Users\z004asyt\workspace\greactions\node_modules\jsdom\lib\jsdom\living\helpers\custom-elements.js:54:3)
>     at HTMLFormElement.removeChild (C:\Users\z004asyt\workspace\greactions\node_modules\jsdom\lib\jsdom\living\generated\Node.js:452:9)
>     at removeChild (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:11099:18)
>     at commitDeletionEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24028:15)
>     at recursivelyTraverseDeletionEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:23989:5)
>     at commitDeletionEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24118:9)
>     at commitDeletionEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:23976:5)
>     at recursivelyTraverseMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24259:9)
>     at commitMutationEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24576:9)
>     at recursivelyTraverseMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24273:7)
>     at commitMutationEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24293:9)
>     at recursivelyTraverseMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24273:7)
>     at commitMutationEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24346:9)
>     at recursivelyTraverseMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24273:7)
>     at commitMutationEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24293:9)
>     at recursivelyTraverseMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24273:7)
>     at commitMutationEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24576:9)
>     at recursivelyTraverseMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24273:7)
>     at commitMutationEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24432:9)
>     at commitMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24243:3)
>     at commitRootImpl (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:26810:5)
>     at commitRoot (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:26682:5)
>     at callback (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:26117:3)
>     at callback (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:12042:22)
>     at flushActQueue (C:\Users\z004asyt\workspace\greactions\node_modules\react\cjs\react.development.js:2667:24)
>     at actImplementation (C:\Users\z004asyt\workspace\greactions\node_modules\react\cjs\react.development.js:2582:11)
>     at C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\react\dist\act-compat.js:63:25
>     at Object.eventWrapper (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\react\dist\pure.js:78:27)
>     at Object.wrapEvent (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\user-event\dist\cjs\event\wrapEvent.js:8:28)
>     at Object.call (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\user-event\dist\cjs\event\dispatchEvent.js:47:22)
>     at Object.dispatchUIEvent (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\user-event\dist\cjs\event\dispatchEvent.js:24:26)
>     at Mouse.up (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\user-event\dist\cjs\system\pointer\mouse.js:91:30)
>     at PointerHost.release (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\user-event\dist\cjs\system\pointer\index.js:74:28)
>     at pointerAction (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\user-event\dist\cjs\pointer\index.js:62:47)
>     at runNextTicks (node:internal/process/task_queues:60:5)
>     at processTimers (node:internal/timers:511:9)
>     at Object.pointer (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\user-event\dist\cjs\pointer\index.js:35:9)
>     at Object.asyncWrapper (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\react\dist\pure.js:71:14)
>     at C:\Users\z004asyt\workspace\greactions\src\components\experiments\tests\ImportExperiments.test.tsx:130:9

Thanks

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
Any jest test that utilizes an Ix input field inside an IxValidationTooltip.
```

### LINKED ISSUE #945: TypeError: Cannot read properties of null (reading 'style') at ValidationTooltip.destroyAutoUpdate
### What happened?

All jest tests that involve interacting with a field utilizing an IxValidationTooltip are failing with the error quoted below. This is a new bug we've found since updating to Ix 2.0.4. It is perhaps related to https://github.com/siemens/ix/issues/944.

> TypeError: Cannot read properties of null (reading 'style')
>     at ValidationTooltip.destroyAutoUpdate (C:\Users\z004asyt\workspace\greactions\node_modules\@siemens\ix\components\src\components\validation-tooltip\validation-tooltip.tsx:78:25)
>     at ValidationTooltip.call (C:\Users\z004asyt\workspace\greactions\node_modules\@siemens\ix\components\src\components\validation-tooltip\validation-tooltip.tsx:188:10)
>     at ValidationTooltip.disconnectedCallback (C:\Users\z004asyt\workspace\greactions\node_modules\@stencil\core\internal\client\index.js:2586:46)
>     at ValidationTooltip.invokeTheCallbackFunction (C:\Users\z004asyt\workspace\greactions\node_modules\jsdom\lib\jsdom\living\generated\Function.js:23:26)
>     at invokeCEReactions (C:\Users\z004asyt\workspace\greactions\node_modules\jsdom\lib\jsdom\living\helpers\custom-elements.js:188:31)
>     at ceReactionsPostSteps (C:\Users\z004asyt\workspace\greactions\node_modules\jsdom\lib\jsdom\living\helpers\custom-elements.js:54:3)
>     at HTMLDivElement.removeChild (C:\Users\z004asyt\workspace\greactions\node_modules\jsdom\lib\jsdom\living\generated\Node.js:452:9)
>     at removeChildFromContainer (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:11105:15)
>     at commitDeletionEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24026:15)
>     at recursivelyTraverseDeletionEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:23989:5)
>     at commitDeletionEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24118:9)
>     at recursivelyTraverseDeletionEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:23989:5)
>     at commitDeletionEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24170:9)
>     at commitDeletionEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:23976:5)
>     at recursivelyTraverseMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24259:9)
>     at commitMutationEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24432:9)
>     at commitMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24243:3)
>     at commitRootImpl (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:26810:5)
>     at commitRoot (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:26682:5)
>     at callback (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:26117:3)
>     at flushSyncCallbacks (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:12042:22)
>     at flushSync (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:26201:7)
>     at ReactDOMRoot.unmount (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:29336:5)
>     at Object.unmount (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\react\dist\pure.js:126:12)
>     at callback (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\react\dist\pure.js:262:12)
>     at callback (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\react\dist\act-compat.js:64:24)
>     at actImplementation (C:\Users\z004asyt\workspace\greactions\node_modules\react\cjs\react.development.js:2512:16)
>     at C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\react\dist\act-compat.js:63:25
>     at forEach (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\react\dist\pure.js:261:27)
>     at Array.forEach (<anonymous>)
>     at cleanup (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\react\dist\pure.js:257:22)
>     at Object.<anonymous> (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\react\dist\index.js:35:24)
>     at Promise.then.completed (C:\Users\z004asyt\workspace\greactions\node_modules\jest-circus\build\utils.js:391:28)
>     at new Promise (<anonymous>)
>     at callAsyncCircusFn (C:\Users\z004asyt\workspace\greactions\node_modules\jest-circus\build\utils.js:316:10)
>     at _callCircusHook (C:\Users\z004asyt\workspace\greactions\node_modules\jest-circus\build\run.js:181:40)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at _runTest (C:\Users\z004asyt\workspace\greactions\node_modules\jest-circus\build\run.js:158:5)
>     at _runTestsForDescribeBlock (C:\Users\z004asyt\workspace\greactions\node_modules\jest-circus\build\run.js:66:9)
>     at _runTestsForDescribeBlock (C:\Users\z004asyt\workspace\greactions\node_modules\jest-circus\build\run.js:60:9)
>     at run (C:\Users\z004asyt\workspace\greactions\node_modules\jest-circus\build\run.js:25:3)
>     at runAndTransformResultsToJestFormat (C:\Users\z004asyt\workspace\greactions\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapterInit.js:170:21)
>     at jestAdapter (C:\Users\z004asyt\workspace\greactions\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:68:19)
>     at runTestInternal (C:\Users\z004asyt\workspace\greactions\node_modules\jest-runner\build\runTest.js:389:16)
>     at runTest (C:\Users\z004asyt\workspace\greactions\node_modules\jest-runner\build\runTest.js:475:34)
>     at Object.worker (C:\Users\z004asyt\workspace\greactions\node_modules\jest-runner\build\testWorker.js:133:12)

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
Any jest test that utilizes an Ix input field inside an IxValidationTooltip.
```

### PR DESCRIPTION
**Pull request by jul-lam**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [x] Unit tests (`yarn test`) were run locally and passed
- [x] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [x] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: [944](https://github.com/siemens/ix/issues/944) | [945](https://github.com/siemens/ix/issues/945)

## What is the new behavior?

The Jest tests no longer fail.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

Manually tested behavior in a separate Gatsby application with a Jest setup.

## Other information

Unit tests have not been added yet, as Jest is required but currently unavailable. Jest may be incorporated in a separate PR.

Closes #944 
Closes #945

### CODE REVIEW

File: packages/core/src/components/validation-tooltip/validation-tooltip.tsx [hunk 1]
```diff
@@ -75,7 +75,9 @@ export class ValidationTooltip {
   }
 
   private destroyAutoUpdate() {
-    this.tooltipElement.style.display = 'none';
+    if (this.tooltipElement) {
+      this.tooltipElement.style.display = 'none';
+    }
```
Comment (nuke-ellington) [inline packages/core/src/components/validation-tooltip/validation-tooltip.tsx:80]: More concise solution?

```suggestion
    this.tooltipElement?.style.display = 'none';
```

Comment (jul-lam) [reply packages/core/src/components/validation-tooltip/validation-tooltip.tsx:80]: The more concise solution is not possible in this case.

image

File: packages/core/src/components/validation-tooltip/validation-tooltip.tsx [hunk 2]
```diff
@@ -187,7 +189,7 @@ export class ValidationTooltip {
     this.observer?.disconnect();
     this.destroyAutoUpdate();
 
-    this.formElement.removeEventListener('submit', this.onSubmitBind);
+    this.formElement?.removeEventListener('submit', this.onSubmitBind);
     this.inputElement.removeEventListener('focus', this.onInputFocusBind);
```
Comment (nuke-ellington) [inline packages/core/src/components/validation-tooltip/validation-tooltip.tsx:193]: Should we not also add a null check to this line?

Comment (jul-lam) [reply packages/core/src/components/validation-tooltip/validation-tooltip.tsx:193]: I wasn't sure if the IxValidationTooltip can be used without an input field. If it can a null check should be added, since this might lead to an error otherwise.

Comment (nuke-ellington) [reply packages/core/src/components/validation-tooltip/validation-tooltip.tsx:193]: I think the problem is that in some test setups timing issues can lead NPEs even if an input was at some point present.

**Review by nuke-ellington — APPROVED** [review]
