### PR TITLE
fix(core/menu-category): expand category if nested item becomes active

### LINKED ISSUE #1436: ix-menu-category not expanding
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

I'm using ix-menu-category for a nested menu

The following has been observed:

- The menu expands if I set active=true on any of the sub menu-items
- The menu expands if I directly hit url of any sub menu-item
- The menu does not expand if I use any internal link within the application to navigate to sub menu-item page

### What type of frontend framework are you seeing the problem on?

React, Others

### Which version of iX do you use?

v2.0.0

### Code to produce this issue.

```shell
import {
  IxApplication,
  IxMenu,
  IxMenuCategory,
  IxMenuItem,
} from '@siemens/ix-react';
import React from 'react';

export default () => {
  return (
    <IxApplication>
      <IxMenu>
        <IxMenuItem home icon="home">
          Home
        </IxMenuItem>
        <IxMenuItem icon="globe">Normal Tab</IxMenuItem>
        <IxMenuCategory label="Top level Category" icon="rocket">
          <IxMenuItem icon="globe" onClick={() => {
                router.push('/path');
              }}
              {...{ active: location.split('/')[1] == 'path' }}>
              Nested Tab</IxMenuItem>
        </IxMenuCategory>
      </IxMenu>
    </IxApplication>
  );
};
```

### PR DESCRIPTION
**Pull request by nuke-ellington**
## 💡 What is the current behavior?

GitHub Issue Number: Closes #1436, [IX-1625]

## 🆕 What is the new behavior?

-
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [x] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [x] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [x] 🧐 Static code analysis passes (`pnpm lint`)
- [x] 🏗️ Successful compilation (`pnpm build`, changes pushed)

### CODE REVIEW

File: packages/core/src/components/menu-category/menu-category.tsx [hunk 1]
```diff
@@ -144,15 +144,32 @@ export class MenuCategory {
...
+        mutation.attributeName === 'class' &&
+        mutation.target instanceof HTMLElement
+      ) {
+        if (mutation.target.classList.contains('active')) {
+          this.showItems = true;
+          this.onExpandCategory(true);
+          return;
+        }
+      }
+    }
```
Comment (matthiashader) [inline packages/core/src/components/menu-category/menu-category.tsx:172]:
```suggestion
    for (const mutation of mutations ?? []) {
      if (
        mutation.attributeName === 'class' &&
        mutation.target instanceof HTMLElement &&
        mutation.target.classList.contains('active')
      ) {
        this.showItems = true;
        this.onExpandCategory(true);
        return;
      }
    }
```

**Review by matthiashader — APPROVED** [review]

**Review by matthiashader — APPROVED** [review]
