### PR TITLE
fix(core/modal): ensure that key down listener gets called

### LINKED ISSUE #848: Modal: not possible to disable close function by clicking on ESC
### What happened?

I tried to set the `keyboard ` config to false, but I can still use ESC button to close the modal if I click on that.

User experience: 
1. Open the modal window
2. Press ESC -> nothing happens (as expected)
3. Click on the dialog(!!!) then press ESC -> modal is closed

Note: I couldn't find description about the `keyboard` config in the documentation, so it is just an assumption that this is how it should work. 

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.3

### Code to produce this issue.

```shell
this.modalService.open({
 content: DialogComponent, keyboard: false
});
```

### PR DESCRIPTION
**Pull request by nuke-ellington**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [x] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [x] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: Closes #848

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: packages/core/src/components/modal/modal.tsx [hunk 1]
```diff
@@ -86,6 +87,13 @@ export class Modal {
    */
   @Event() dialogDismiss: EventEmitter;
 
+  @OnListener<Modal>('keydown', (self) => !self.keyboard)
```
Comment (danielleroux) [inline packages/core/src/components/modal/modal.tsx:90]: Why is global event listener here necessary?

**Review by danielleroux — CHANGES_REQUESTED** [review]
Component test is missing

File: packages/core/src/components/modal/modal.tsx (hunk 1 above)
Comment (nuke-ellington) [reply packages/core/src/components/modal/modal.tsx:90]: Because the onKey listener will only get called when the dialog has focus. Clicking on it removes the focus.

**Review by danielleroux — APPROVED** [review]
