### PR TITLE
fix(core/card-list): adapt title margin to figma

### LINKED ISSUE #1491: CardList is different in figma & code
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Code:
image
& it is delivered with 8px margin around, this causes disadvantage for developers because they can't align it

image
Figma

The main difference is, that the space from headline to cards is different. Additionally from my point of view the space from the arrow to the headline is too big. And what happens if I have more elements but no detail page? can this whole component be used to expand like a blind?

### What type of frontend framework are you seeing the problem on?

Others

### Which version of iX do you use?

Figma

### Code to produce this issue.

```shell
-
```

### PR DESCRIPTION
**Pull request by matthiashader**
## 💡 What is the current behavior?
- Margin from header to card-list is 8px -> 0.5rem

GitHub Issue Number: Closes #1491, 

## 🆕 What is the new behavior?

-  Margin from header to card-list is 16px -> 1rem

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

### CODE REVIEW

**Review by danielleroux — CHANGES_REQUESTED** [review]
- [x] Reduce `strict` errors

**Review by nuke-ellington — APPROVED** [review]

**Review by nuke-ellington — APPROVED** [review]

File: packages/core/src/components/card-list/card-list.tsx [hunk 1]
```diff
@@ -283,7 +283,7 @@ export class CardList {
       <Host>
         <CardListTitle
           isCollapsed={this.collapse}
-          label={this.label}
+          label={this.label!}
```
Comment (danielleroux) [inline packages/core/src/components/card-list/card-list.tsx:286]: See sonarcloud report

**Review by danielleroux — CHANGES_REQUESTED** [review]

**Review by danielleroux — APPROVED** [review]
