### PR TITLE
fix(core/ix-menu-category): dynamic added items not visible

### LINKED ISSUE #1606: ix-menu-category dynamic items are not visible
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

In our sidenav menu, we have a list of favorite items (`ix-menu-category`). Users can modify this and the list should be instantly updated. However, if the list is expanded and the user tries to add more than one item they are not visible.

I think the issue might be related to the fact that you set a fixed `max-height` on that element during [animation](https://github.com/siemens/ix/blob/77f76febbc00df91a3d27f43845f2cfadd9234ac/packages/core/src/components/menu-category/menu-category.tsx#L124).

There is a [code snippet](https://stackblitz.com/edit/kreyvq?file=src%2Findex.html) based on the example for [2nd navigation level](https://ix.siemens.io/docs/controls/application-frame/application-menu?current-tab=development#2nd-navigation-level). To see the issue:
- expand the menu,
- expand the 'Top level Category',
- add multiple items by clicking the 'Add item' button a few times,
- only the first item will be visible.

ix-menu-issue

### What type of frontend framework are you seeing the problem on?

JavaScript

### Which version of iX do you use?

2.6.0

### Code to produce this issue.

```shell
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Menu category example</title>
    <link rel="stylesheet" href="./menu-category.css" />
  </head>
  <body>
    <ix-application force-breakpoint="lg">
      <ix-menu>
        <ix-menu-item home icon="home">Home</ix-menu-item>
        <ix-menu-item icon="globe">Normal Tab</ix-menu-item>
        <ix-menu-category label="Top level Category" icon="rocket">
          <ix-menu-item icon="globe">Nested Tab</ix-menu-item>
          <ix-menu-item icon="globe">Nested Tab</ix-menu-item>
        </ix-menu-category>
      </ix-menu>
      <ix-button>Add item</ix-button>
    </ix-application>

    <script type="module">
      (async () => {
        await window.customElements.whenDefined('ix-menu');
        const menu = document.querySelector('ix-menu');
        const category = document.querySelector('ix-menu-category');
        const button = document.querySelector('ix-button');

        menu.breakpoints = ['medium'];

        button.addEventListener('click', () => {
          const item = document.createElement('ix-menu-item');
          item.icon = 'globe';
          const newContent = document.createTextNode('Nested Tab');
          item.appendChild(newContent);
          category.append(item);
        });
      })();
    </script>
    <script type="module" src="./init.js"></script>
  </body>
</html>
```

### PR DESCRIPTION
**Pull request by lzeiml**
## 💡 What is the current behavior?

Dynamic list of items visualized through the ‘ix-menu-item’ in the ‘ix-menu-category’ are not getting updated when new items are added, only after reopening the menu-category the items appear.

GitHub Issue Number: Closes #1606, [IX-2202](https://agileworld.siemens.cloud/jira/browse/IX-2202)

## 🆕 What is the new behavior?

- Container height of ix-menu-category is now updated when items are added/removed, making dynamically added items visible

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

### CODE REVIEW

**Review by danielleroux — COMMENTED** [review]
Please add some component tests to verify the fix.

**Review by danielleroux — CHANGES_REQUESTED** [review]
Please add some component tests to verify the fix.

File: packages/core/src/components/menu-category/menu-category.tsx [hunk 1]
```diff
@@ -126,6 +126,10 @@ export class MenuCategory {
         this.showItems = true;
         this.showDropdown = false;
       },
+      complete: () => {
+        this.menuItemsContainer!.removeAttribute('max-height');
```
Comment (nuke-ellington) [inline packages/core/src/components/menu-category/menu-category.tsx:130]: Just out of curiosity:

Is this line necessary considering that the `max-height` will get set in the `setMenuItemsContainerMaxHeight` fn immediately afterwards?

File: .changeset/beige-files-switch.md [hunk 2]
```diff
@@ -0,0 +1,7 @@
+---
+"@siemens/ix": patch
+---
+
+The max-height of __ix-menu-category__ is adjusted for dynamically added items. Dynamically added items are now visible.
```
Comment (nuke-ellington) [inline .changeset/beige-files-switch.md:5]:
```suggestion
 __ix-menu-category__: Dynamically added items are now instantly visible. This is achieved by adjusting the max-height everytime an item gets added.
```

**Comment by lzeiml** [comment]
@danielleroux 
> Please add some component tests to verify the fix.

https://github.com/siemens/ix/pull/1706/commits/76f62c13f7e160bcdccaad5d84ebef3a92c0cd10

File: packages/core/src/components/menu-category/test/menu-category.ct.ts [hunk 3]
```diff
@@ -320,3 +320,52 @@ test('show category if item are focused', async ({ mount, page }) => {
...
+    const newMenuItem2 = document.createElement('ix-menu-item');
+
+    newMenuItem1.textContent = 'Dynamically Added';
+    newMenuItem2.textContent = 'Dynamically Added';
+
+    menuCategory?.appendChild(newMenuItem1);
+    menuCategory?.appendChild(newMenuItem2);
+  });
+
+  await page.waitForTimeout(300);
```
Comment (AndreasBerliner) [inline packages/core/src/components/menu-category/test/menu-category.ct.ts:361]: Using timeouts should be avoided.

File: packages/core/src/components/menu-category/menu-category.tsx [hunk 4]
```diff
@@ -151,8 +151,19 @@ export class MenuCategory {
   }
 
   private onNestedItemsChanged(mutations?: MutationRecord[]) {
+    const oldNestedItemsLength: number = this.nestedItems.length;
```
Comment (matthiashader) [inline packages/core/src/components/menu-category/menu-category.tsx:154]: i think we dont need this
```suggestion
    const oldNestedItemsLength = this.nestedItems.length;
```

**Review by matthiashader — CHANGES_REQUESTED** [review]

File: packages/core/src/components/menu-category/test/menu-category.ct.ts (hunk 3 above)
Comment (lzeiml) [reply packages/core/src/components/menu-category/test/menu-category.ct.ts:363]: I just added another timeout. Without them the height measurement is very inaccurate/inconsistent because of the animation that menu-category uses. Do you have another idea?

Comment (matthiashader) [reply packages/core/src/components/menu-category/test/menu-category.ct.ts:363]: I think smth like this could work: 
```suggestion
  //When the animation is done also the opacity is set to one
    await page.waitForSelector(
    'div.menu-items.menu-items--expanded[style*="opacity: 1"]'
  );
  
  ....
  
  //The second time we could check if the foruth children is visible:
    await page.waitForSelector('ix-menu-category ix-menu-item:nth-child(4)', {
    state: 'visible',
  });

```

**Review by matthiashader — DISMISSED** [review]

File: packages/core/src/components/menu-category/test/menu-category.ct.ts [hunk 5]
```diff
@@ -320,3 +320,59 @@ test('show category if item are focused', async ({ mount, page }) => {
...
+        <ix-menu-category label="Category label">
+          <ix-menu-item>Test</ix-menu-item>
+          <ix-menu-item>Test</ix-menu-item>
+        </ix-menu-category>
+      </ix-menu>
+    </ix-application>
+  `);
+
+  await page.locator('ix-menu-expand-icon').click();
+  await page.locator('ix-menu-category').click();
```
Comment (nuke-ellington) [inline packages/core/src/components/menu-category/test/menu-category.ct.ts:340]: This way you don't have to call locator/querySelector multiple times
```suggestion
  const menuCategory = page.locator('ix-menu-category');
  await menuCategory.click();
```

File: packages/core/src/components/menu-category/test/menu-category.ct.ts [hunk 6]
```diff
@@ -320,3 +320,59 @@ test('show category if item are focused', async ({ mount, page }) => {
...
+
+  // wait for the menu expand animation to be finished
+  await page.waitForSelector(
+    'div.menu-items.menu-items--expanded[style*="opacity: 1"]'
+  );
+
+  const initialHeight: number | undefined = await page
```
Comment (nuke-ellington) [inline packages/core/src/components/menu-category/test/menu-category.ct.ts:347]: Typing not necessary here
```suggestion
  const initialHeight = await page
```

File: packages/core/src/components/menu-category/test/menu-category.ct.ts [hunk 7]
```diff
@@ -320,3 +320,59 @@ test('show category if item are focused', async ({ mount, page }) => {
...
+  });
+
+  const newHeight: number | undefined = await page
+    .locator('ix-menu-category')
+    .boundingBox()
+    .then((box) => box?.height);
+
+  expect(initialHeight).toBeDefined();
+  expect(newHeight).toBeDefined();
+  expect(newHeight).toBeGreaterThan(initialHeight!);
```
Comment (nuke-ellington) [inline packages/core/src/components/menu-category/test/menu-category.ct.ts:377]: We should come up with a better assertion criterion. Maybe the exact height we expected?

**Review by nuke-ellington — CHANGES_REQUESTED** [review]

**Review by nuke-ellington — APPROVED** [review]
