### PR TITLE
fix(core/tooltip|dropdown): find trigger if in same shadow DOM

### LINKED ISSUE #1530: Tooltip not working with shadowDOM
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Tooltips are not visible when hovering over the button with shadow DOM enabled for the component

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.5.0

### Code to produce this issue.

```shell
https://stackblitz.com/edit/n9auvb?file=src%2Ftooltip.ts
```

### PR DESCRIPTION
**Pull request by nuke-ellington**
## 💡 What is the current behavior?

GitHub Issue Number: Closes #1530, [IX-1885]

## 🆕 What is the new behavior?

-
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [x] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [x] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [x] 🧐 Static code analysis passes (`pnpm lint`)
- [x] 🏗️ Successful compilation (`pnpm build`, changes pushed)

### CODE REVIEW

**Review by matthiashader — CHANGES_REQUESTED** [review]
changeset missing & strict typing (if its necessary inside an unit test)

File: packages/core/src/components/utils/find-element.ts [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+
+  if (elementsInSlot.length > 0) {
+    return Promise.resolve(elementsInSlot);
+  }
+
+  const elementsInShadowRoot: HTMLElement[] = Array.from(
+    shadowRoot.querySelectorAll(selector)
+  );
+
+  return Promise.resolve(elementsInShadowRoot);
```
Comment (jul-lam) [inline packages/core/src/components/utils/find-element.ts:48]:
```suggestion
  if (elementsInShadowRoot.length > 0) {
    return Promise.resolve(elementsInShadowRoot);
  }
  
  return Promise.resolve(undefined);
```

**Review by jul-lam — CHANGES_REQUESTED** [review]

**Review by matthiashader — DISMISSED** [review]

**Review by danielleroux — APPROVED** [review]

**Review by jul-lam — APPROVED** [review]
