### PR TITLE
fix(core/drawer): start show true

### LINKED ISSUE #647: Drawer is not shown if initialized with [show]=true
### What happened?

I want to show the drawer per default opened and i used the following lines of code:

`    <ix-drawer [fullHeight]="true" [closeOnClickOutside]="true" [show]="true">
      <span>Some content of drawer</span>
    </ix-drawer>`

the drawer has still display: none; set, if I use the toggle button and initialize it with [show]=false everything works as expected.

image

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.4.0

### Code to produce this issue.

```shell
`    <ix-drawer [fullHeight]="true" [closeOnClickOutside]="true" [show]="true">
      <span>Some content of drawer</span>
    </ix-drawer>`
```

### PR DESCRIPTION
**Pull request by goncalosard**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: closes #647

## What is the new behavior?

- Now when show prop starts true, drawer starts opened correctly

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: packages/core/src/components/drawer/drawer.tsx [hunk 1]
```diff
@@ -146,6 +146,10 @@ export class Drawer {
     });
   }
 
+  componentDidRender() {
```
Comment (danielleroux) [inline packages/core/src/components/drawer/drawer.tsx:149]: Please check  https://stenciljs.com/docs/component-lifecycle#componentdidrender `componentDidRender` looks not like a good place to do this.

**Review by danielleroux — CHANGES_REQUESTED** [review]

**Review by danielleroux — APPROVED** [review]
