### PR TITLE
fix(core/general): small fixes

### LINKED ISSUE #1349: ag grid, active on hover is not aligned with ix design.
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

See the difference between on hover over an active tree on hover and active ag grid on hover.

image

I've looked inside your source code and was unable to achive the ag grid color with using predefined ghosts.

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.2.1

### Code to produce this issue.

```shell
See, click to make items active, then hover over with mouse.

https://ix.siemens.io/docs/controls/tree
https://ix.siemens.io/docs/controls/grid
```

### LINKED ISSUE #1371: Breaking change - ix-group-item does not handle click event
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

After updating from 2.0.4 to 2.3.0 the click event on ix-group-item does not gets fired. `suppressSelection` is set to true on the group item because of #915 (I am using custom logic to decide which group item should be selected and wrote custom css to highlight the selected item.) Before the update the click event handler was working fine. Now it is not working if `suppressSelection` is true.

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

2.3.0

### Code to produce this issue.

```shell
<ix-group
  *ngFor="let group of packageGroups; trackBy: trackByPackageId"
  suppressHeaderSelection="true"
  [collapsed]="!group.extended"
>
  <ix-group-item
    *ngFor="let package of group.packages; trackBy: trackById"
    suppressSelection="true"
    [selected]="package.id === selectedPackage?.id"
    [class.customSelected]="package.id === selectedPackage?.id"
    (click)="onPackageSelect(package)" <-- this is not working if suppressSelection is true
  >
    <div>
      ...
    </div>
  </ix-group-item>
</ix-group>
```

### PR DESCRIPTION
**Pull request by matthiashader**
## 💡 What is the current behavior?

This PR resolves some small issues identified in the last dev sync

GitHub Issue Number: Closes #1371, Small fix from #1368, Fixes #1349, [IX-1441]

## 🆕 What is the new behavior?

- ix-group-item deleted the pointer-events: none -> Now clickable, but not selectable
- ag-grid -> removed background-color -> was applied 2 time one time by the element, one time by the pseudo element
- documentation -> corrected link to the documentation
- title of application-header has now body-lg

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

### CODE REVIEW

File: packages/core/src/components/group-item/group-item.tsx [hunk 1]
```diff
@@ -60,18 +60,15 @@ export class GroupItem {
...
    * Index
    */
-  @Prop() index: number;
+  @Prop() index?: number;
 
   @Listen('click', { passive: true })
   clickListen() {
-    if (this.suppressSelection) {
-      return;
-    }
```
Comment (danielleroux) [inline packages/core/src/components/group-item/group-item.tsx:74]: Removing this will start trigger event handler on parent. This should no happen if suppressSelection is set

File: packages/core/src/components/group-item/group-item.tsx [hunk 2]
```diff
@@ -60,18 +60,15 @@ export class GroupItem {
   /**
    * Selection changed
    */
-  @Event() selectedChanged: EventEmitter<HTMLIxGroupItemElement>;
+  @Event() selectedChanged?: EventEmitter<HTMLIxGroupItemElement>;
```
Comment (danielleroux) [inline packages/core/src/components/group-item/group-item.tsx:63]: Event is not optional.

File: packages/core/src/components/group-item/group-item.tsx [hunk 3]
```diff
@@ -49,7 +49,7 @@ export class GroupItem {
   /**
    * Show selected state
    */
-  @Prop() selected: boolean;
+  @Prop() selected?: boolean;
```
Comment (danielleroux) [inline packages/core/src/components/group-item/group-item.tsx:52]:
```suggestion
  @Prop() selected: boolean = false;
```

**Review by danielleroux — CHANGES_REQUESTED** [review]

File: packages/core/src/components/group-item/group-item.tsx (hunk 1 above)
Comment (matthiashader) [reply packages/core/src/components/group-item/group-item.tsx:74]: added corresponding logic inside the parent

**Review by nuke-ellington — APPROVED** [review]
