### PR TITLE
fix(core/blind): remove blind content after collapse changed

### LINKED ISSUE #519: iXblinds title vanishes with tab key
### What happened?

I got a bug when trying to move to an iXblind by using the tab key. Usually users should be able to navigate along controls without a mouse, just by keyboard (in case of tablet devices). I found out that it is not possible to move to an iXblind by tab key. When klicking onto an iXblind with the mouse and pressing the tab key, the iXblind title is no more visible. The expected behaviour should be that using the tab key an iXblind can become the active control and expanding/collapsing is done by using the enter or space key.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.4.2

### Code to produce this issue.

_No response_

### PR DESCRIPTION
**Pull request by danielleroux**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: Closes #519

## What is the new behavior?

Remove `<slot></slot>` when collapsed

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

File: packages/core/src/components/blind/blind.tsx [hunk 1]
```diff
@@ -171,7 +171,7 @@ export class Blind {
               hide: this.collapsed,
             }}
           >
-            <slot></slot>
+            {!this.collapsed ? <slot></slot> : null}
```
Comment (nuke-ellington) [inline packages/core/src/components/blind/blind.tsx:174]: Without running the code I wonder: will this mess with the animation?
