### PR TITLE
fix: dropdown positioning

### LINKED ISSUE #1348: Animating transition in container, breaks select position calculation.
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

We are our own custom modals and they are mimicking the ix ones.

However placing <ix-select>, breaks the calculation when there is transition animation effect.

image

Ofcourse, when we disable the transition it works. 

How is the position of the select calculated? If wontfix we might opt into mimicking the ix-select as well.

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.2.1

### Code to produce this issue.

```shell
Iside a container that arrivers on screen using transition effect.


.dialog {
  animation: fade-in .2s forwards;
}

.fade-out {
    animation: fade-out .2s forwards;
}

@keyframes fade-out {
  0% {
    opacity: 1;
  }

  100% {
    opacity: 0;
    translate: 0 -50px;
  }
}

@keyframes fade-in {
  0% {
    opacity: 0;
    translate: 0 -50px;
  }

  100% {
    opacity: 1;
  }
}
```  

<ix-select>
    <ix-select-item label="Item 1" value="1"></ix-select-item>
    <ix-select-item label="Item 1" value="2"></ix-select-item>
  </ix-select>
```

### PR DESCRIPTION
**Pull request by jul-lam**
## 💡 What is the current behavior?

GitHub Issue Number: Closes #1348, [IX-1449]

- dropdown positioning breaks inside floating-ui (dialog)

## 🆕 What is the new behavior?

- dropdowns are now correctly positioned inside floating-ui elements

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

### CODE REVIEW

File: packages/angular-test-app/src/test/utils/wait-for-timeout.ts
Comment (AndreasBerliner) [inline packages/angular-test-app/src/test/utils/wait-for-timeout.ts:1]: This seems to be unused.

**Review by AndreasBerliner — COMMENTED** [review]
The PR does not introduce a fix, but includes refactorings and tests the behavior.

File: .changeset/heavy-cups-peel.md [hunk 1]
```diff
@@ -0,0 +1,5 @@
+---
+"@siemens/ix": patch
+---
+
+Fix __ix-dropdown__ position inside floating ui
```
Comment (danielleroux) [inline .changeset/heavy-cups-peel.md:5]:
```suggestion
Update `@floating-ui/dom` dependency to fix a wrong placement of the `ix-dropdown` if the dropdown is placed inside a `dialog`-element with padding.
```

Comment (jul-lam) [inline .changeset/heavy-cups-peel.md:5]:
```suggestion
Update `@floating-ui/dom` dependency to fix a wrong placement of the `ix-dropdown` if the dropdown is placed inside a `dialog`-element with animations in certain environments.
```

**Review by danielleroux — APPROVED** [review]
