### PR TITLE
fix(core): avoid initial validation of required boolean input types

### LINKED ISSUE #1801: Issues with input elements
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [x] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Hi,
I am implementing forms in our applications using your components. I've noticed a few issues with them. Please let me know if this is something you will address in the near future or if maybe I am misusing them.

I provide a [stackblitz](https://stackblitz.com/edit/mt8dddxl?file=src%2Findex.html) with all the issues and examples.

The provided code is based on an example of an input element from your documentation.

### What type of frontend framework are you seeing the problem on?

JavaScript

### Which version of iX do you use?

v2.7.0

### Code to produce this issue.

```shell
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Input example</title>
    <style>
      body {
        height: 100vh;
        overflow: auto;
      }
    </style>
  </head>
  <body>
    <h3>TEXT INPUT</h3>
    <ul>
      <li>Required input is invalid even without any interactions.</li>
      <ix-input
        label="Required"
        placeholder="Required input"
        required
        invalid-text="Required"
      ></ix-input>
      <li>Min length validation is not updated</li>
      <ix-input
        id="min-length"
        placeholder="Min len (3)"
        min-length="3"
      ></ix-input>
      <p id="min-length-info"></p>
    </ul>

    <h3>CHECKBOX</h3>
    <ul>
      <li>Required checkbox is always marked as invalid</li>
      <li>Label is missing the error styling (is not red) and asterisk (*)</li>
      <li>Missing invalid-text property (only on checkbox-group)</li>
      <li>Nice to have - label position property (at least top and right)</li>
      <ix-checkbox
        label="Required"
        invalid-text
        required
        invalid-text="Required"
      ></ix-checkbox>
    </ul>

    <h3>NUMBER INPUT</h3>
    <ul>
      <li>Required input is marked as invalid for 0</li>
      <ix-number-input required label="Input"></ix-number-input>
      <li>
        Just an example of the opposite behavior - min value does not mark the
        input as incorrect until user interaction
      </li>
      <ix-number-input id="min" min="4" max="10"></ix-number-input>
      <li>Step property is missing.</li>
    </ul>

    <h3>DATE INPUT</h3>
    <ul>
      <li>Time input is missing</li>
      <li>Required is invalid without any interactions</li>
      <ix-date-input
        required
        label="Date"
        invalid-text="Required"
      ></ix-date-input>
    </ul>

    <h3>TEXTAREA</h3>
    <ul>
      <li>Required input is invalid even without any interactions</li>
      <ix-textarea
        label="Textarea"
        required
        min-length="3"
        max-length="10"
      ></ix-textarea>
    </ul>

    <h3>RADIO</h3>
    <ul>
      <li>Required is not working (no asterisk)</li>
      <ix-radio-group label="Storage options" required>
        <ix-radio
          label="256GB SSD storage"
          value="256"
          name="storage-256gb"
          required
        ></ix-radio>
        <ix-radio
          label="512GB SSD storage"
          value="512"
          name="storage-512gb"
        ></ix-radio>
        <ix-radio
          label="2TB SSD storage"
          value="2048"
          name="storage-2tb"
          disabled
        ></ix-radio>
      </ix-radio-group>
    </ul>
    <script type="module" src="./init.js"></script>
  </body>
</html>
```

### PR DESCRIPTION
**Pull request by danielleroux**
## 💡 What is the current behavior?

GitHub Issue Number: Fixes #1801 

## 🆕 What is the new behavior?

- Avoid initial validation of required boolean components (ix-radio, ix-checkbox, ix-toggle)
- Handle group validation of radio and checkbox
- Show required indicator (*) for ix-radio-group and ix-checkbox-group

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [x] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [x] 🏗️ Successful compilation (`pnpm build`, changes pushed)

### CODE REVIEW

File: packages/core/src/components/radio-group/radio-group.tsx [hunk 1]
```diff
@@ -142,8 +156,15 @@ export class RadiobuttonGroup
     });
   }
 
+  private checkRequiredOfRadioComponent() {
```
Comment (nuke-ellington) [inline packages/core/src/components/radio-group/radio-group.tsx:159]:
```suggestion
  private hasNestedRequiredRadio() {
```

**Review by nuke-ellington — CHANGES_REQUESTED** [review]
Looks like Angular, React & Vue should get a version bump, too?

**Comment by danielleroux** [comment]
> Looks like Angular, React & Vue should get a version bump, too?

image

`@siemens/ix` is forced to align with the other packages

**Review by nuke-ellington — APPROVED** [review]
